[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monoio = { workspace = true }
local-sync = { workspace = true }
slog = { workspace = true }
slog-async =  { workspace = true }
slog-term =  { workspace = true }
bytes = { workspace = true }