[versions]
guava = "31.1-jre"
flatbuffers-java = "23.3.3"
junit-jupiter = "5.9.2"
#for test. 4.x is used since 5.x requires jdk 11+.
mockito-core = "4.11.0"
commons-lang3 = "3.12.0"
netty-all = "4.1.90.Final"
log4j = "2.20.0"
kafka-clients = "3.4.0"
grpc = "1.54.0"
tomcat-annotations-api = "6.0.53"
google-protoc = "3.22.2"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
flatbuffers-java = { module = "com.google.flatbuffers:flatbuffers-java", version.ref = "flatbuffers-java" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty-all" }

#used for logging
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-clients" }

# used for grpc
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-testing = { module = "io.grpc:grpc-testing", version.ref = "grpc" }
#necessary for Java 9+
tomcat-annotations-api = { module = "org.apache.tomcat:annotations-api", version.ref = "tomcat-annotations-api" }

google-protoc = { module = "com.google.protobuf:protoc", version.ref = "google-protoc" }

[bundles]
#used for logging
log4j = ["log4j-api", "log4j-core", "log4j-slf4j2-impl"]

[plugins]
protoc-grpc = { id = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }