---
# Server configuration
server:
  # Advertise host address
  host: "127.0.0.1"
  # Listening port
  port: 10911
  # Number of Thread-per-Core Nodes
  concurrency: 1
  uring:
    # Network io_uring queue depth
    queue-depth: 128
  # Placement manager address
  placement-manager: "127.0.0.1:2378"
# Store configuration
store:
  # Whether mkdirs if missing
  mkdirs-if-missing: true
  # Store directory
  path:
    # Base path of the store, containing lock, immutable properties and other configuration files
    base: "/data/store"
    # Directory of WAL segment files. It could be absolute or relative to `base`
    wal: "wal"
    # Directory of metadata RocksDB files. It could be absolute or relative to `base`
    metadata: "metadata"
  # 1GiB
  segment-size: 1073741824
  # Max block cache size
  max-cache-size: 1073741824
  #alignment
  alignment: 4096
  # Preferred IO read size: 128KiB
  read-block-size: 131072
  # Pre-allocated number of segment files
  pre-allocate-segment-file-number: 2
  # io_uring setup
  uring:
    # IO io_uring queue depth
    queue-depth: 1024
    # Kernel SQ Poll thread will quit if it remains idle for 2 seconds.
    sqpoll-idle-ms: 2000
    # Bind the kernel's poll thread to the specified cpu.
    sqpoll-cpu: 1
    # Kernel thread pool size for bounded tasks. Note this thread pool is 
    # shared with server `Node`s.
    max-bounded-worker: 2
    # Kernel thread pool size for unbounded tasks. Note this thread pool is
    # shared with server `Node`s.
    max-unbounded-worker: 2
  # RocksDB configuration items
  rocksdb:
    # Create column families if missing
    create-if-missing: true
    # Flush index entries of record-batch every `flush_threshold`
    flush-threshold: 32768
