# PM Configuration.

# urls for peer traffic
peerUrls: http://127.0.0.1:2380
# urls for client traffic
clientUrls: http://127.0.0.1:2379
# advertise urls for peer traffic
advertisePeerUrls: http://127.0.0.1:2380
# advertise urls for client traffic
advertiseClientUrls: http://127.0.0.1:2379

# human-readable name for this PM member
name: pm-hostname
# path to the data directory
dataDir: default.pm-hostname
# the initial cluster configuration for bootstrapping
initialCluster: pm=http://127.0.0.1:2380
# the address of sbp server
sbpAddr: 127.0.0.1:2378
# expiration time of the leader, in seconds
leaderLease: 3
# time interval for checking the leader's priority
leaderPriorityCheckInterval: 60000000000 # 1 minute

etcd:
  # set different tokens to prevent communication between PMs in different clusters
  initialClusterToken: pm-cluster
  # interpret 'auto-compaction-retention' one of: periodic|revision
  autoCompactionMode: periodic
  # auto compaction retention for mvcc key value store
  autoCompactionRetention: 1h
  # Any configuration in embed.Config can also be set here
  #tickMs: 500
  #electionMs: 3000
  #...

log:
  # the minimum enabled logging level
  level: INFO
  # whether to enable log rotation
  enableRotation: false
  zap:
    # a list of URLs or file paths to write logging output to
    outputPaths:
      - stderr
    # a list of URLs to write internal logger errors to
    errorOutputPaths:
      - stderr
    # the logger's encoding, "json" or "console"
    encoding: json
    # Any configuration in zap.Config can alse be set here
    #disableCaller: false
    #disableStacktrace: false
    #encoderConfig:
    #  messageKey: msg
    # ...
  rotate:
    # maximum size in megabytes of the log file before it gets rotated
    maxSize: 64
    # maximum number of days to retain old log files based on the timestamp encoded in their filename
    maxAge: 180
    # maximum number of old log files to retain, default is to retain all old log files (though MaxAge may still cause them to get deleted)
    maxBackups: 0
    # whether the time used for formatting the timestamps in backup files is the computer's local time, default is to use UTC time
    localTime: false
    # whether the rotated log files should be compressed using gzip
    compress: false
