[package]
name = "placement-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raft = "0.6"
num_cpus = "1"
byteorder = "1"