[package]
name = "data-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder =  { workspace = true }
bytes =  { workspace = true }
core_affinity =  { workspace = true }
crc =  { workspace = true }
monoio =  { workspace = true }
num_cpus =  { workspace = true }
thiserror =  { workspace = true }
crossbeam =  { workspace = true }
clap = { workspace = true }
num_enum =  { workspace = true }
dashmap =  { workspace = true }
seahash =  { workspace = true }
slog =  { workspace = true }
slog-async =  { workspace = true }
slog-term =  { workspace = true }
codec = { path = "../components/codec" }
transport = { path = "../components/transport" }
