[package]
name = "data-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_affinity = "0.7"
monoio = "0.0"
num_cpus = "1"
thiserror = "1.0"
crossbeam = "0.8"
clap = { version = "4.0", features = ["derive"] }
