name: Build all platforms

on: workflow_call
permissions: read-all

jobs:
  crossbuild:
    strategy:
      matrix:
        go-version: [ "1.19" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Go Cache
      uses: actions/cache@v3
      with:
        path: .go/cache
        key: ${{matrix.platform}}-${{matrix.go-version}}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{matrix.platform}}-${{matrix.go-version}}-go-build-
          ${{matrix.platform}}-${{matrix.go-version}}-go-
    - name: Build containers
      run: make all-container GO_VERSION=${{ matrix.go-version }}
