name: CI - Run lint

on: workflow_call
permissions: read-all

jobs:
  lint:
    strategy:
      matrix:
        go-version: [ "1.19" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Go Cache
      uses: actions/cache@v3
      with:
        path: .go/cache
        key: ${{matrix.platform}}-${{matrix.go-version}}-go-lint-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{matrix.platform}}-${{matrix.go-version}}-go-lint-
          ${{matrix.platform}}-${{matrix.go-version}}-go-
    - name: Lint
      run: make lint GO_VERSION=${{ matrix.go-version }}
