name: Continuous Integration

on: push

jobs:
  skip_check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: 'true'
  lint:
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci-lint.yaml
  build:
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/ci-crossbuild.yaml
  test:
    uses: ./.github/workflows/ci-tests.yaml
